@startuml

title 鼠标穿透执行机制流程

start
:开始;

if (当前鼠标是否在贴图窗口内?) is (是) then
    if (判断当前贴图窗口是否已穿透?) is (已穿透) then
      :取消该贴图窗口的穿透状态;
    else (未穿透)
      :设置该贴图窗口为穿透状态;
    endif
else (否)
    :取消所有贴图窗口的穿透状态;
endif

:结束;
stop

@enduml